global:
    scrape_interval: 5s

scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets: [ 'localhost:9090' ]

    - job_name: my_metrics
      scrape_interval: 1s
      static_configs:
          - targets: ['worker:8000']