version: '3.7'

volumes:
    prom-volume:
    grafana_vol:

services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana_vol:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    environment:
      - GF_LOG_LEVEL=error

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prom-volume:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /cgroup:/cgroup:ro  # only for Linux

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
#      - '--path.rootfs=/rootfs'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  work_stress1:
    image: progrium/stress
    container_name: stress-cpu
    command: [--cpu, '1', --timeout, '240s', --backoff, '10000000', --quiet]

  work_stress2:
    image: progrium/stress
    container_name: stress-io
    command: [--io, '2', --timeout, '360s', --backoff, '8000000', --quiet]

  work_stress3:
    image: progrium/stress
    container_name: stress-mem1
    command: [--vm, '1', --vm-bytes, '128M', --timeout, '330s', --backoff, '5000000', --quiet]

  work_stress4:
    image: progrium/stress
    container_name: stress-mem2
    command: [--vm, '2', --timeout, '120s', --backoff, '14000000', --quiet]

  work_stress5:
    image: progrium/stress
    container_name: stress-disk1
    command: [--hdd, '1', --timeout, '90s', --backoff, '9000000', --quiet]

  work_stress6:
    image: progrium/stress
    container_name: stress-disk2
    command: [--hdd, '2', --hdd-bytes, '256M', --timeout, '315s', --backoff, '12000000', --quiet]
