version: '3.7'

volumes:
    prom-volume:
    grafana_vol:

services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana_vol:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    environment:
      - GF_LOG_LEVEL=error

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prom-volume:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /cgroup:/cgroup:ro  # only for Linux

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
#      - '--path.rootfs=/rootfs'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  work_stress1:
    image: progrium/stress
    container_name: dejan
    command: [--cpu, '4', --io, '4', --vm, '4', --vm-bytes, '128M', --timeout, '90s']

  work_stress2:
    image: progrium/stress
    container_name: dejan2
    command: [--cpu, '1', --io, '1', --vm, '1', --timeout, '180s']
