global:
    scrape_interval: 5s

scrape_configs:

    - job_name: 'my_process'
      scrape_interval: 10ms
      static_configs:
          - targets: ['my_metrics:8000']

    - job_name: 'cadvisor'
      scrape_interval: 5s
      static_configs:
        - targets:
            - cadvisor:8080