global:
    scrape_interval: 5s

scrape_configs:

    - job_name: 'my_process'
      scrape_interval: 1s
      static_configs:
        - targets:
          - host.docker.internal:8000
          - workload:8000

    - job_name: 'cadvisor'
      scrape_interval: 5s
      static_configs:
        - targets:
            - cadvisor:8080